### ISSUE TITLE
Пропускать приведение типов если это не нужно

### ISSUE THREAD

**Issue by atomoc** [AgelxNash/DocLister#120]
Изменить core/extender/tv.extender.inc[203]:
```php
$item[0] = $this->DocLister->changeSortType($field, isset($sortType[$i]) ? $sortType[$i] : null);
```
на:
```php
if (count($sortType) > 0){
    $st = count($sortType) > 1 ? $sortType[$i] : implode($sortType);
} else {
    $st = null;
}
$item[0] = $this->DocLister->changeSortType($field, $st);
```

**Comment by AgelxNash** [comment]
Приведение типов определяется порядком. Например: ```&orderBy=`count DESC, price ASC` &tvSortType=`,SIGNED` ```, получим ```count DESC, CAST(`price` as SIGNED)```

А вот в случае ```&orderBy=`count DESC, price ASC` &tvSortType=`SIGNED,SIGNED` ```, результатом уже будет ```CAST(`count` as SIGNED) DESC, CAST(`price` as SIGNED)```

**Comment by atomoc** [comment]
Что это значит, что ```&tvSortType=`SIGNED` &orderBy=`count DESC, price ASC` ``` будет ```CAST(`count` as SIGNED) DESC, CAST(`price` as SIGNED)``` ? Или как?

Просто если как- то иначе, то будет неясно, а чтобы догадаться что нужно запятую поставить перед выражением надо быть провидцем.

**Comment by atomoc** [comment]
Понял. Это для того, чтобы не иметь возможность не указывать вообще. Ну не знаю, это важно?
