### ISSUE TITLE
Ошибка с параметром &showParent

### ISSUE THREAD

**Issue by vvp24** [AgelxNash/DocLister#121]
Ошибка возникает при 
&showParent=`1` и &idType=`parents`
При этом выводится еще и ресурс-корень всего каталога
Версия самая новая (в предыдущих такого не было)

**Comment by AgelxNash** [comment]
Параметр showParent для это и придуман. В предыдущих версиях этот параметр как раз-таки и игнорировался. Т.к. этот параметр заранее известен, его можно исключить через addWhereList

**Comment by AgelxNash** [comment]
Вопрос разрешен #124.
Чтобы активировать прежнюю логику, необходимо значение параметра *showParent* сменить на **-**1
