### ISSUE TITLE
Баг fs::toOct()

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#123]
Для 0644 функция возвращает неверное значение.
Чтобы корректно работало, нужно передавать $chmod как строку.

**Comment by AgelxNash** [comment]
Добавил тесты для этого метода - все прошли успешно. Добавил даже [тесты с отрицанием](https://github.com/AgelxNash/DocLister/commit/0e875d1ca50a764304976c10ffbcbe7f099f3000) - и они прошли успешно
https://travis-ci.org/AgelxNash/DocLister/builds/50483100
https://travis-ci.org/AgelxNash/DocLister/builds/50483341

**Comment by Pathologic** [comment]
В том и проблема, что с 0755 все в порядке. Протестируй с 0644.

**Comment by Pathologic** [comment]
0644 => string(3) "272"
644 => string(3) "420"
"0644" => string(3) "420"
"644" => string(3) "420"

**Comment by AgelxNash** [comment]
Да, действительно. Обновил тесты и они отвалились. Странно, что в случае с 755 все работает как нужно.

**Comment by Pathologic** [comment]
Мне кажется, что метод не нужен. Сейчас он вызывается для обработки параметра $perms в методах makeDir и copyFile, и при этом допускается неопределенность в типе этого параметра, которая устраняется методом toOct. А в чем смысл эту неопределенность вообще допускать? 
Если $perms задавать строкой, то проблема решается сама собой и, более того, для преобразования будет достаточно функции octdec.

**Comment by AgelxNash** [comment]
Думаю ты прав. Если параметр строка - то применяем преобразование. Если же это число, то оставляем как есть и тут уже нужно самостоятельно следить в какой системе счисления указаны права.
