### ISSUE TITLE
Дополнительный idType

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#124]
После правки https://github.com/AgelxNash/DocLister/commit/029e5e6276c0928b532d0ea2a892354b55feac1a стало неудобно выводить из onetable. В SimpleGallery я использую поле sg_rid для связи с таблицей site_content и раньше можно было указать parentField и parents чтобы в выборку попали нужные значения. А теперь в запрос добавляется OR sg_id или AND sg_id и приходится использовать addWhereList: https://github.com/Pathologic/SimpleGallery/commit/53eb8b082bd4e1b28e86d1608db18e2e7ca5972f
Может стоит добавить idType=`resources`, resourceField=``, resources=`1,2,3` в контроллер onetable?

**Comment by AgelxNash** [comment]
Теперь параметр showParent воспринимает 3 значения:
- **-1** как было до https://github.com/AgelxNash/DocLister/commit/029e5e6276c0928b532d0ea2a892354b55feac1a
- **0** принудительное игнорирование родителей в выборке
- **1** принудительное добавление родителя в выборку
