### ISSUE TITLE
modUsers - ошибка в методе edit();

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#127]
https://github.com/AgelxNash/DocLister/blob/master/assets/lib/MODxAPI/modUsers.php#L80 - не проверяется результат запроса, поэтому даже если пользователь не найден по корректному $id, то метод все равно вернет объект вместо false.

**Comment by AgelxNash** [comment]
Это же самое относится и к modResource.

**Comment by AgelxNash** [comment]
Вспомнил я с какой целью это делалось. Идея была такая, чтобы после вызова метода ->edit() не приходилось разывать цепочку. 
Сейчас можно написать так
```php
$user->edit(10)->set('blocked', 1)->save(true, true);
```
В то время, как если edit будет возвращать то объект, то false. Придется делать как-то так
```php
if($user->edit(10) !== false) $user->set('blocked', 1)->save(true, true);
```

В общем если после открытия записи требуется проверить - существует ли она, то нужно использовать метод ->getID().

Так что это не баг, а такой хардкорный синтаксический сахар)
