### ISSUE TITLE
Баг в пагинаторе

### ISSUE THREAD

**Issue by vvp24** [AgelxNash/DocLister#132]
При "пустом" пагинаторе выводиться обертка пагинатора. До обновления не выводилось

**Comment by AgelxNash** [comment]
После вот этого [коммита](https://github.com/AgelxNash/DocLister/commit/dfe1e884da70e51e64d95a77b87e88931ce694a6) не могу воспроизвести баг. Он еще актуален?

**Comment by vvp24** [comment]
Да, актуален на текущей версии. Выводит TplWrapPaginate при отсутствии страниц на пагинацию

**Comment by toha-proud** [comment]
Подтверждаю, на последней версии этот баг присутствует, ели нет страниц, то выводится обертка.
