### ISSUE TITLE
MODxAPI::escape портит json

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#140]
Обнаружилось после переноса сайта на хостинг с включенными магическими кавычками. Если в json содержится юникод, то stripslashes в методе удаляет слэши из символов \uXXXX и значение портится. Отключение кавычек решает проблему, но раз в методе предусмотрена проверка их наличия - значит имеется баг :smile_cat:

**Comment by AgelxNash** [comment]
С одной стороны корректное экранирование _REQUEST данных. А с другой стороны ломающийся json... Все это было актуально, когда DocLister и MODxAPI запускались на php 5.2.
