### ISSUE TITLE
DocLister - не работает параметр prepareWrap

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#147]
В методе renderWrap: 
```
$extPrepare = $this->getExtender('prepare');
```
$extPrepare = null, если не изменить вызов на getExtender('prepare',true).

**Comment by AgelxNash** [comment]
Несколько раз пользовался этим параметром - все работало. У тебя в вызове обычного prepare параметра нет?

**Comment by Pathologic** [comment]
Нет, только prepareWrap
