### ISSUE TITLE
Документировать изменения

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#149]
Занести в файл HISTORY.md изменения которые были проделаны @Pathologic

**Comment by Pathologic** [comment]
Можно их вписать в 2.1.23?

**Comment by AgelxNash** [comment]
Да

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/DocLister/commit/a5d3b433d9bf747ea5ccc9d4542b7e733dc97d80 :+1:
