### ISSUE TITLE
Минификация JS и CSS на лету

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#150]
При наличии сниппета [MinifyX](https://github.com/AgelxNash/MinifyX-for-Evolution) можно производить сжатие в [SimpleTab\Plugin::renderJS](https://github.com/AgelxNash/DocLister/blob/master/assets/lib/SimpleTab/plugin.class.php#L107) на лету. Типа такого:
```php
$modx->runSnippet('MinifyX', array(
	'outFolder'=>'assets/templates/',
	'outJS'=>'simpleTab.min.js',
	'outCSS'=>'simpleTab.min.css',
	'CSSfile'=>'
		assets/js/fancybox/jquery.fancybox.css,
		assets/templates/v1/css/custom.css',
	'JSfile'=>'assets/js/jquery.ikSelect.js,
		assets/js/jquery.maskedinput.min.js,
		assets/js/fancybox/jquery.fancybox.pack.js,',
	'jsCompress'=>'1',
	'cssCompress'=>'1'
));
```
После чего на вывод отдавать только assets/templates/simpleTab.min.js и assets/templates/simpleTab.min.css.

**Comment by Pathologic** [comment]
Что-то мне кажется, что выигрыша заметного не будет, зато будет геморрой с отладкой. Проблема, по-моему, не в том, что скрипты несжатые, а в том, что они в админке загружаются через жопу и приходится делать костыли типа renderJS. По-хорошему нужен контроллер, который бы собирал из плагинов скрипты, хтмл, а потом брал шаблон и рендерил страницу в админке, хоть со сжатием, хоть без него, а не тупорылые mutate.php. А так костыли как ни развивай, все равно они костыли и есть.
