### ISSUE TITLE
Некорректная сортировка

### ISSUE THREAD

**Issue by Typodin** [AgelxNash/DocLister#154]
Не работает сортировка с параметрами:

&orderBy=`pub_date DESC`

или, например

&sortBy=`menuindex`
&order=`DESC` 

А если использовать в качестве параметра id то все нормально.
Версия сборки 1.1b-d7.1.2 , DocLister из репозитория - 2.1.0

**Comment by Pathologic** [comment]
Лучше не использовать DocLister из репозитория, потому что актуальная версия 2.1.23.
&sortDir=`DESC` - так правильно

**Comment by Typodin** [comment]
Скачал и переустановил отсюда.

Вариант с &orderBy=`pub_date DESC` не заработал.

&sortBy=`pub_date`
&sortDir=`DESC`

а также 

&sortBy=`pub_date`
&order=`DESC`
(на всякий проверил)

Так и не работают корректно

**Comment by Pathologic** [comment]
Да, &order есть такой параметр :smile: Нужно запускать с &debug и смотреть какой запрос получается.

**Comment by AgelxNash** [comment]
@Typodin получилось разобраться?

**Comment by Typodin** [comment]
Да получилось. Это особенность DocLister - если документ создан путем копирования, то ему не присваивается автоматически значение menuindex и DocLister не может сортировать по нему. При этом Ditto вполне себе сортирует, учитывая фактическое расположение пунктов в меню, которые задаются через DocManager. Так что эту проблему скорее можно отнести к недостаточной гибкости.
