### ISSUE TITLE
DLcrumbs - минимальное число элементов

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#160]
Если hideMain=0 и showCurrent=1, то возможна ситуация, когда в крошках будет только один элемент - текущая страница. По-моему это не нормально, во всяком случае я не сталкивался с необходимостью такого вывода крошек. Можно или ввести ограничение на минимум два элемента или ввести параметр minCrumbs (2 по умолчанию).

**Comment by AgelxNash** [comment]
Первый раз сталкиваюсь с такой проблемой. Ну чисто теоретически - это можно сделать и без правок DLCrumbs:
- Получить плейсхолдер с кол-вом выводимых документов. И там решить - показывать результат работы сниппета или нет
- В prepare получить общее кол-во доков. И там уже принимать решение какие данные возвращать из prepare: false или $data.
