### ISSUE TITLE
Лимит выводимых документов DocLister

### ISSUE THREAD

**Issue by info-e** [AgelxNash/DocLister#166]
Предлагается предусмотреть параметр, например, limit с назначением - ограничение общего количества выводимых документов. При этом выводимые документы должны иметь возможность  выводиться с пагинацией, например
`[!DocLister? ... &display=`50`&paginate=`pages`&limit=`200`... !]
[+pages+]`

**Comment by Pathologic** [comment]
Параметр называется maxDocs.
