### ISSUE TITLE
Добавить вызов событий в modUsers

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#167]
- [x] ~~OnBeforeWebLogin~~
- [x] OnBeforeWebLogout
- [x] OnWebAuthentication
- [x] OnWebChangePassword
- [x] OnWebDeleteUser
- [x] OnWebLogin	
- [x] OnWebLogout
- [x] OnWebSaveUser

**Comment by Pathologic** [comment]
C событием OnBeforeWebLogin не понятно, что делать. И для чего оно вообще нужно, тоже - плагинов на это событие я не нашел.

**Comment by Pathologic** [comment]
OnWebAuthentication добавил в метод testAuth() - результат метода запрещает или разрешает авторизацию, что соответствует логике вызова события. Соответственно и remember в событие передавать нет смысла, вряд ли этот параметр как-то может повлиять на запрет авторизации.

**Comment by AgelxNash** [comment]
OnBeforeWebLogin Вызывается в сниппете WebLogin: https://github.com/modxcms/evolution/blob/master/assets/snippets/weblogin/weblogin.processor.inc.php#L193-L199
```php
$modx->invokeEvent("OnBeforeWebLogin", array(
          "username"        => $username,
          "userpassword"    => $givenPassword,
          "rememberme"    => $rememberme
));
```

**Comment by Pathologic** [comment]
Зачем оно вообще нужно,  если результат вызова не проверяется. Получается что копия события OnWebLogin.

**Comment by AgelxNash** [comment]
OnWebLogin срабатывает когда юзер уже авторизован. А OnBeforeWebLogin ты можешь допустим логировать попытку авторизоваться и блокировать все что дальше будет отправляя в die.

Еще один сценарий -  при авторизации клиент может выбрать что-то вроде типа учетной записи. Для частного лица используется таблица web_users штатно. А для юр.лиц какая-то другая таблица. Так вот, если выбран способ авторизоваться как юр.лицо, то плагин onBeforeWebLogin перехватывает попытки и как-то на них реагирует отвечая редиректами. Если же выбран частник, то плагин просто ничего не делает.

**Comment by AgelxNash** [comment]
Немного запутался. https://github.com/AgelxNash/DocLister/commit/7c3fd76f47e7d694b357b7b2dd5d17f20fd8bcc5 коммит уже не актуален?

**Comment by Pathologic** [comment]
Коммиты хотел по одному добавлять, но что-то пошло не так :disappointed: Может лучше будет сразу готовые правки прислать?

**Comment by AgelxNash** [comment]
Собери, пожалуйста, все в одной ветке. Я гляну что и как там.

**Comment by Pathologic** [comment]
Блокировку и логирование можно делать в OnWebAuthentication, а в примере с юрлицами мне кажется нужна уже другая совсем модель. Да и метод getLoginUserID работать не будет.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/pull/188

**Comment by Pathologic** [comment]
OnBeforeWebLogin пусть разработчик вызывает сам. Чтобы вызвать как в WebLogin, нужно вызывать в testAuth, а там нет rememberme; в Auth есть rememberme, но нет пароля.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/pull/191/commits/44a27d963e412df8497d8066dfec43443e485485

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/44a27d963e412df8497d8066dfec43443e485485
