### ISSUE TITLE
pageLimit глючит

### ISSUE THREAD

**Issue by toha-proud** [AgelxNash/DocLister#169]
Необходимо вывести 5 страниц в пагинатре по 40 на странице
Конструкция такого вида выводит 22 страницы
```
&pageLimit=`5`
&display=`40`
```
Чтобы вывести 5 страниц пришлось прибегнуть к конструкции

`&pageLimit=`25`
&display=`40`
`

Что есть совсем не правильно

**Comment by AgelxNash** [comment]
Так и не смог воспроизвести. Поиграйтесь еще с pageAdjacents.

P.S. Класс пагинатора написан не мной, а __Victor De la Rocha__ еще в далеком 2007 году. Каша там знатная. Сейчас автор свой класс не поддерживает, а переписывать его без особой нужны не очень хочется, поскольку на 99% сайтах все работает как и положено. Если есть подходящая рабочая альтернатива или мысли как исправить ваш баг - предлагайте.
