### ISSUE TITLE
Поддержка групп в modUsers

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#174]

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/commit/2e2afdadf91b96ef65912f594cbb0ad01773547c#diff-278504bcf824d59895fe466808bdd9c9R62

**Comment by AgelxNash** [comment]
Хорошая идея. Ведь получение информации есть, а установки нет:-(

**Comment by Pathologic** [comment]
Список групп в метод наверное лучше будет массивом передавать? А то в админке нет никаких ограничений на имя группы.

**Comment by AgelxNash** [comment]
Ну да. Явно вызываем метод для связи юзера с группами. А там пусть кодер решает от куда он этот список ID групп будет получать.
