### ISSUE TITLE
modResource->delete не удаляет дочерние ресурсы

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#184]

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/01bd32516354338d04ef68d64217db4ee989cb9c

**Comment by AgelxNash** [comment]
$modx->getLoginUserID() не учитывает контекст. В итоге если ресурс будет удаляться с фронта, то в базе сохранится корректный id. НО! При изучении логов мы будем думать, что ресурс удален администратором с таким же id, а это могут быть разные пользователи.

Так что тут 2 варианта
- мы явно указываем контекст и учитываем только админов $modx->getLoginUserID('mgr'). При этом нам не важно из какого контекста удаляется документ. В базу попадет ID авторизованного менеджера.
- Структура site_content такова, что deletedby может быть отрицательным. Поэтому если удаление происходит веб-пользователем, то id сохраняем как отрицательное значение.

**Comment by Pathologic** [comment]
А вот это не для учета контекста?
```
switch(true){
    			case ($this->isFrontend() && isset ($_SESSION['webValidated'])):{
    				$out = $_SESSION['webInternalKey'];
    				break;
    			}
    			case ($this->isBackend() && isset ($_SESSION['mgrValidated'])):{
    				$out = $_SESSION['mgrInternalKey'];
    				break;
    			}
    		}
```

**Comment by Pathologic** [comment]
То есть можно сделать еще раз проверку isFrontend(), чтобы можно было дописать минус.

**Comment by AgelxNash** [comment]
Можно и так, но тогда получится так:
- **Менеджер в админке**: 1
- **Менеджер на фронте** если не авторизован как пользователь: 0
- **Пользователь на фроне**: -1

Я предполагаю, что мы должны получить следующий результат:
- **Менеджер в админке**: 1
- **Менеджер на фронте** если не авторизован как пользователь: 1
- **Пользователь на фроне**: -1

**Comment by Pathologic** [comment]
Тут, пожалуй, придется следовать существующей кривой реализации, что менеджеры только в админке, а пользователи только на фронте. Я так понимаю, что менеджеры на фронте это скорее исключение, чтобы они могли смотреть неопубликованные документы.

**Comment by AgelxNash** [comment]
Ну поскольку мы строим "идеальную" систему поверх существующей, то почему бы не создать новый "правильный" метод? Тем более он не ломает обратную совместимость.

**Comment by Pathologic** [comment]
Не ломает, но возникают новые вопросы. Например, каких менеджеров считать полноценными веб-пользователями, а каких нет? Как быть с группами? Ну и у меня проверки всюду с getLoginUserID('web'), то есть придется еще учитывать, что менеджеры тоже хотят удалять документы с фронта (:
Но можно поступить проще - использовать значение $this->field['deletedby'], а разработчик конечного решения сам пусть думает, что туда записывать.

**Comment by Pathologic** [comment]
Вот еще я придумал вариант. Простой пользователь не может быть одновременно залогинен и в админке и на фронте, значит в deletedby можно смело записывать id залогиненного менеджера, главное ведь определить кто удалил документ.

**Comment by AgelxNash** [comment]
Ну я поэтому и не стал рассматривать 4 вариант (пользователь в админке). Я поднял эту тему скорее из-за эстестических  соображений. Чтобы на берегу разрешить проблемы, когда метод вызвал обычный пользователь, а глядя в базе мы будем думать, что удаление (или что-то другое) совершил менеджер под тем же ID.

Поэтому и хочу определиться, как мы будем делать: будем записывать только id менеджеров. Для этого будет достаточно использовать ```$this->modx->getLoginUserID('mgr');```
Либо же мы будем пытаться определить помимо id еще и контекст (для этого понадобятся отрицательные значения). Но как я уже выше писал, один частный случай упускается (менеджер на фронте не авторизован как обычный пользователь). Поэтому нужен свой метод.

К слову, jot экстендер для ditto умеет понимать [отрицательные значения в createdby полях](https://github.com/modxcms/evolution/blob/089ff85f718e72cc2d80fb6cbde8793506a14e7b/assets/snippets/ditto/extenders/jotdatesort.extender.inc.php#L34-L43)
