### ISSUE TITLE
DocLister: Баг в &sortType=`doclist`

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#189]
Вот еще прислал сегодня @Grinyaha
> ПРивет. Не знаешь почему в ДЛ при одновременном использовании
> &sortType=`doclist` И &filters=`tv:amount:!=:0` выдает ошибку?
> 
> SQL > SELECT c.* FROM `kalina94_shop`.`modx_site_content` as `c` LEFT JOIN `kalina94_shop`.`modx_site_tmplvar_contentvalues` as `dltv_amount_1` ON `dltv_amount_1`.`contentid`=`c`.`id` AND `dltv_amount_1`.`tmplvarid`=35 WHERE `dltv_amount_1`.`value` != '0' AND c.id IN ('274','1022') AND c.deleted=0 AND c.published=1 GROUP BY c.id ORDER BY FIND_IN_SET(id,'274,1022')

Я так понимаю, что в FIND_IN_SET должно быть c.id

**Comment by AgelxNash** [comment]
Самое простое решение, заменить `$this->getPK()` на `{$this->getCFGDef('sortBy', $this->getPK())}` а к вызовам с фильтрами добавлять ```sortBy=`c.id````
Не совсем красиво, т.к. кроме c.id ничего и нельзя указать для такого типа сортировки. Но зато быстро решаем проблему.
