### ISSUE TITLE
Поддержка twig в чанках

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#200]

**Comment by AgelxNash** [comment]
Я так понимаю это будет просто новая собака-операция в DLTemplate без притягивания за уши всех классов. Верно?

**Comment by Pathologic** [comment]
Можно собаку, можно просто проверять доступность твига и парсить через него.

**Comment by AgelxNash** [comment]
Мне кажется лучше через собаку. Это 100% не сломает совместимость. У меня допустим есть несколько сайтов с твигом на борту, но вызовы DL работают пор по старинке

**Comment by Pathologic** [comment]
Тут даже лучше не отдельную собаку вводить, а добавить, например, букву T к существующим.

**Comment by AgelxNash** [comment]
+1

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/599ae86ddf700e2b60a1cfaa5c40646ebaaa41b8
https://github.com/AgelxNash/DocLister/commit/e60970eb3b1c4eab8437fa5ec71588cd6ec0f606
https://github.com/AgelxNash/DocLister/commit/9cc65ec2ee4ce2a1c901679da5cc96f6247d8f91
https://github.com/AgelxNash/DocLister/commit/294a0aaa210d00191ccf9fd0bf9e8b4af340b4df
