### ISSUE TITLE
TplFirstP и TplLastP (внезапно появившиеся) развалят верстку при обновлении DL

### ISSUE THREAD

**Issue by webber12** [AgelxNash/DocLister#210]
Неплохо бы их сделать по умолчанию пустыми или отключенными, т.к. внезапно появившиеся новые ссылки в другой стилистике могут развалить верстку после обновления на каком-нибудь старом сайте

https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/extender/paginate.extender.inc#L135-L137

**Comment by Pathologic** [comment]
Можно пустыми, почему бы и нет. Я как бы не против (:

**Comment by webber12** [comment]
Я бы лучше через какой нибудь параметр вроде FirstLastPageShow сделал по аналогии с PrevNextAlwaysShow
if ($this->DocLister->getCFGDef("FirstLastPageShow", 0) == '1') {}

**Comment by webber12** [comment]
Или в конфиг paginate внести их заполненными https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/config/core/paginate.json - иначе потом забудутся сами плейсхолдеры [%paginate.first%] и [%paginate.last%] :)

**Comment by AgelxNash** [comment]
Есть возможность формить PR как ты это видишь?

**Comment by webber12** [comment]
Насчет PR - тут на обсуждение, как лучше. Либо оставить как есть сейчас - по-умолчанию пустые, но дозаполнить эти 2 новых параметра TplFirstP и TplLastP в конфиге paginate тут https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/config/core/paginate.json либо оставить так, как было сначала - заполненные в самом экстендере параметры, но обернуть в доп.проверку как это сделано с PrevNextAlwaysShow - т.е. обернуть их объявление в какой-то блок

```
if ($this->DocLister->getCFGDef("FirstLastPageShow", 0) == '1') {
    ...
}
```
Т.е. основной смысл в том, чтобы, с одной стороны, обнулить их значения по умолчанию, а с другой - хоть где-то оставить новые плейсхолдеры [%paginate.first%] и [%paginate.last%]

**Comment by AgelxNash** [comment]
Лично мне кажется, что лучше без еще одного параметра. Их и так в DL пруд пруди, а обнулить данные можно и обычным пустым шаблоном.

**Comment by webber12** [comment]
Ну значит оставить как есть сейчас (с пустым шаблоном по умолчанию в экстендере), но добавить эти 2 параметра (заполненные) в json-конфиг paginate

**Comment by Pathologic** [comment]
Вариант с конфигом неплох, можно вынести туда вообще все шаблоны пагинации.

**Comment by webber12** [comment]
Да, потому только про новые и говорю - чтобы не забыть, что там такие плейсхолдеры вообще есть. А то вчера смотрю - появились уже на моем парфюмерном сайте лишние ссылки в пагинации, да еще и "не той системы" :))

**Comment by Pathologic** [comment]
То что в вызове перекрывает конфиг.
