### ISSUE TITLE
Проверять id сессии в методе modUsers::AutoLogin

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#213]
http://modx.im/blog/security/4743.html#comment37495

**Comment by Pathologic** [comment]
sessionid обновляется при сохранении пользователя, обновлять каждый час или как-то еще - дело разработчика.

**Comment by AgelxNash** [comment]
@Pathologic в чем баг?
Вообще, в плане безопасности MODX не самый лучший движок. От SQL-injection до произвольного вполнения кода - рукой подать. А мы тут будем заморачиваться регенерацией сессии, чтобы ее не украли?
В общем если раньше работало, а сейчас не работает - предлагаю откатить и не морочить голову.
