### ISSUE TITLE
DLTemplate - ошибка 500 с твиг-чанками

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#231]
Первый вызов завершается ошибкой, потом чанк попадает в кэш и проблема исчезает. Что-то не то с загрузчиком шаблонов.

**Comment by AgelxNash** [comment]
Посмотри приоритеты плагинов. Может в этом дело.

**Comment by Pathologic** [comment]
Нет, там немного сложнее.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/EvoTwig/issues/4
