### ISSUE TITLE
Проблемы с сессией после #213

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#232]
https://github.com/AgelxNash/DocLister/commit/c69c0eb9e4a6a413676ca2ec4794ca506efc630c - пока думаю вот на это.

**Comment by Pathologic** [comment]
В лучшем случае слетает авторизация, в худшем - ошибка 500, пока не удалю siteCache. В логах появляется ошибка, что не удается загрузить класс кэша Doctrine.

**Comment by AgelxNash** [comment]
Озвучил свои мысли по этому поводу в соседнем тикете https://github.com/AgelxNash/DocLister/issues/213

**Comment by Pathologic** [comment]
Закрою оба, потому что скорее всего это у меня какие-то проблемы с сервером - раз больше никто не жалуется.

**Comment by AgelxNash** [comment]
Просто скорее всего никто не использует авторизацию через modUsers. Да я и сам на MODX давно сайты не собирал с авторизацией, поэтому на практике проверить тоже не могу.

**Comment by Pathologic** [comment]
Используют, @dmi3yy вот сейчас как раз сайт делает.

**Comment by dmi3yy** [comment]
По сессии есть проблема когда одновременно и админ и веб пользователь то через какое то время разлогинивает но это думаю гдетто в самом Модх проблема 

Отправлено с iPhone
