### ISSUE TITLE
Не хватает возможности присоединения таблиц в DocLister

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#233]
Пока делаю хаком в onetable, но нужно продумать возможность сделать нормально. Пока что мешают фильтры в site_content, которые сами джойнят таблицы.

**Comment by AgelxNash** [comment]
Я думал об этом когда пытался переписать DL. Сколько ни пробовал - всегда велосипед получался. Единственное нормально работающие решение - под задачу сделать свой контроллер в котором по умолчанию подключить нужные таблицы.

Так что как бы заманчиво не звучало предложение, я все-таки склоняюсь пока к контроллерам, а не программированию через параметры.

**Comment by Pathologic** [comment]
Да, я тоже попытался и пришел к выводу, что очень много нужно переписывать, так что проще костылить под задачу, тем более, что и задачи такие не часто встречаются.
