### ISSUE TITLE
Контроллер onetable и idType="parents"

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#234]
Так как метод setIDs в этом контроллере не переопределяется, то родители выбираются из site_content, а потом по ним делается выборка уже в таблице, заданной для onetable. По идее это баг, но для компонентов типа SimpleGallery, это уже фича. Возможно стоит как-то упорядочить это поведение.

**Comment by AgelxNash** [comment]
Не понял вопроса. setIDs определена в абстрактном [классе DocLister и только](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1228). Если мы используем контроллер site_content, то при вызове метода getChildrenFolder из sitIDs мы уходим [сюда](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L399). Если же используется контроллер onetable, то уходим уже в [другой класс](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/onetable.php#L360). Не пойму, как мы из onetable вдруг попадаем в site_content...

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L241 - вот отсюда путаница пошла. Просто указать таблицу в свойстве table недостаточно, потому что это свойство перезапишется значением параметра. У меня получилось так:
```
protected $table = 'my_table';

public function __construct(DocumentParser $modx, array $cfg, $startTime = null)
    {
        parent::__construct($modx, $cfg, $startTime); //здесь в свойство table записалось значение site_content, с учетом этого отработал метод setIDs
        $this->table = $this->getTable('my_table'); //приходится заново задавать свойство table
        ...
    }
```
