### ISSUE TITLE
orderBy  не работет с сортировкой по TV, притом в версии 2.0.7 работает корректно

### ISSUE THREAD

**Issue by dmi3yy** [AgelxNash/DocLister#236]
https://monosnap.com/file/5WUdocsnMq5QKYYli7s8KkLoqr3kfC

**Comment by AgelxNash** [comment]
Вызов сниппета в студию.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/94903591399ccf555e3b19aea607796df500556f

**Comment by dmi3yy** [comment]
Спасибо теперь работает
