### ISSUE TITLE
Метод getUserIP (assets/lib/APIHelpers.class.php)

### ISSUE THREAD

**Issue by poh-am** [AgelxNash/DocLister#237]
Вызов метода getUserIP начиная с php версии 5.4.x приводит к ошибке типа WARNING: 
"Non-static method APIHelpers::_getEnv() should not be called statically"
Возможно, следует изменить вызов метода _getEnv, например следующим образом:

```
$class = new self();
 switch (true) {
/*         case ($tmp = self::_getEnv('HTTP_COMING_FROM')):
                $out = $tmp;
                break;
            case ($tmp = self::_getEnv('HTTP_X_COMING_FROM')):
                $out = $tmp;
                break;
*/
             case ($tmp = $class->_getEnv('HTTP_COMING_FROM')):
                $out = $tmp;
                break;
            case ($tmp = $class->_getEnv('HTTP_X_COMING_FROM')):
                $out = $tmp;
...
}
```

либо сделать метод _getEnv статическим

**Comment by AgelxNash** [comment]
Спасибо. Вообще, можно переделать на замыкание, чтобы избавиться от этого одноразового метода. PHP 5.2 уже не поддерживаем, поэтому...
