### ISSUE TITLE
Пагинация при использовании кастом роутинга. Вопрос как коректней сделать а то пока пришлось говнокодить 

### ISSUE THREAD

**Issue by dmi3yy** [AgelxNash/DocLister#238]
Суть задачи: 
запилил фильтр на базе eFiter  у которых урл: 

site.com/catalog/param1/param2/paramN/ 
при то что плагин работает в итоге через $modx->sendForward($id); 
(Тоесть доклистер видит урл site.com/catalog/) вернее он его генерит у себя по $id

пришлось вот https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/lib/DLpaginate.class.php#L287 
допилить: 
http://take.ms/g9ir1

`     global $modx;
        if (isset($_GET['page'])){
            $url = str_replace(array( '&page='.$_GET['page'], '?page='.$_GET['page'] ), array('',''), $_SERVER['REQUEST_URI']);
        }else{
            $url = $_SERVER['REQUEST_URI'];
        }
        $this->target = $url;
`

C учетом того что вариант сео урлов для фильтра очень полезная штука и реализация через кастомный роутинг довольно простая то хотелось бы решить вопрос.

**Comment by AgelxNash** [comment]
Если честно, я не совсем понимаю задачу. Какого вида ложна быть ссылка пагинатора?
И да, никто не запрещает сделать свой экстендер пагинации и внедрить в него сей хак. И будет это уже не хак))

**Comment by dmi3yy** [comment]
А пни в нужну сторону по части экстендера 
на страничке 
ite.com/catalog/param1/param2/paramN/

должно быть 
site.com/catalog/param1/param2/paramN/?page=2 
а было 
site.com/catalog/?page=2

**Comment by AgelxNash** [comment]
Задать ссылку относительно которой будет формировать пагинатор можно через метод target https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/extender/paginate.extender.inc#L157 по умолчанию эта ссылка формируется автоматически по базовому правилу.

Т.е. ты можешь сделать копию базового экстендера пагинации paginate_DL_Extender, подменить в нем метод getUrl() и подключить твой новый файл через include до вызова DocLister (лучшим способом будет автозагрузка на событии OnWebPageInit). Из минусов - этот пагинатор будет применен для всего сайта, а не для конкретного вызова.

А вообще, я могу попробовать добавить параметр чтобы можно было на лету метод getUrl подменять.

**Comment by dmi3yy** [comment]
Смотри там по логике всего 2 варианта: 
- генерим на базе $id 
- генерим на базе $_SERVER['REQUEST_URI']

так как пагинация по факту это добавление 1 параметра поэтому 3 варианта как генерить урл что б был какой то вариант не вижу. 

По части что так будет работать для всего сайта не проблема ибо при базовом использовании и 1 и 2 вариант отдают один и тот же урл

**Comment by dmi3yy** [comment]
Вот так по логике переписать и все 
http://take.ms/XefmZ
ну и параметр добавить

**Comment by dmi3yy** [comment]
Если утвердишь сделаю пул

**Comment by AgelxNash** [comment]
В целом все так, но мне не нравится подход в использовании REQUEST_URI. Во первых, в пагинатор может вызываться для другой страницы. Во вторых, в там может быть все что угодно...

**Comment by dmi3yy** [comment]
Так базовая логика не меняется тоесть так будет только при условии использования параметра + если нужно можно еще вариант добавить хотя я пока не представляю какой

Отправлено с iPhone

**Comment by AgelxNash** [comment]
Дай мне время подумать до завтра как это лучше и гибче сделать.

**Comment by dmi3yy** [comment]
Ок. 


От 11 марта 2017 г. в 19:33:45, Евгений Борисов (notifications@github.com) написал:

Дай мне время подумать до завтра как это лучше и гибче сделать.

**Comment by AgelxNash** [comment]
Добавил новый параметр через который можно полностью подменить ссылку на пагинатор. Как пример, вызвать сниппет с пагинацией на главной, но ссылки пагинатора будут уводить в раздел новости с каким-то дополнительным GET параметром.
```
'makePaginateUrl' => function($data, $modx, $_DL, $_eDL){
   return $modx->makeUrl(14).'?filter=off';
},
```

**Comment by dmi3yy** [comment]
Спасибо большое работает запилил в eFilterResult 

`$params['makePaginateUrl'] = function($data, $modx, $_DL, $_eDL){
	$url = explode('?', $_SERVER['REQUEST_URI']);
	return $url['0'];
};`
