### ISSUE TITLE
Номер итерации и номер документа

### ISSUE THREAD

**Issue by Aharito** [AgelxNash/DocLister#239]
В контроллерах site_content, shopkeeper и onetable начальный номер итерации задается как **$i = 1**
[site_content](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L94)
[onetable](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/onetable.php#L63)
[shopkeeper](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/shopkeeper.php#L46)

Затем этот номер передается в uniformPrepare
[site_content](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L158)
[onetable](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/onetable.php#L108)
[shopkeeper](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/shopkeeper.php#L107)

Но в самом uniformPrepare i [по дефолту установлено **в 0**](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1008)

У меня создалось ощущение, что предусматривалась возможность создания своих контроллеров, где итерация будет начинаться с 0, а не с 1.

На эту мысль меня также наводит тот факт, что [в этой строке 0 считается **нечетным**](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1012), то есть как бы  **1-м** документом в списке.

Но если это так, тогда этому [противоречит эта строка](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1023), где жестко записано, что 1-й элемент - это элемент с номером итерации 1.

Отсюда идет неверное определение шаблонов **tplOdd** и **tplEven** в DocLister, а также путаница с первым **tplIdN** (0 или 1). В доках эти шаблоны начинаются с **tplId0**, в реальности во всех контроллерах с **tplId1**.

Если я неправ в своем предположении, что предусматривалась возможность начинать нумерацию док-тов (и соотв. шаблонов) с 0, и начальное **$i всегда будет 1**, то достаточно просто исправить [эту строку](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1012), поменяв == 0 на == 1.

Если же прав, то, возможно, нужно разделить понятия "номер итерации" ($i) и "номер документа" (пусть будет $num), итерация будет с 0, а номер так, как задано - с 0 или с 1. И соответственно добавить функции uniformPrepare аргумент $start (откуда стартует номер док-та - с 0 или 1).

**Comment by Pathologic** [comment]
> Если я неправ в своем предположении, что предусматривалась возможность начинать нумерацию док-тов (и соотв. шаблонов) с 0, и начальное $i всегда будет 1, то достаточно просто исправить эту строку, поменяв == 0 на == 1.

Это исправление позволяет правильно определить четность итерации: если остаток от деления на 2 равен 1, то нечетная (odd), иначе - четная (even).

А чтобы нумерация начиналась с нуля, нужно исправить в контроллерах начальное значение $i.

**Comment by Pathologic** [comment]
Но раз tplId0 никто не использует из-за этой путаницы с $i, то может и не нужно ничего исправлять (кроме определения четности и документации)?

**Comment by Aharito** [comment]
Я использую, вот в чем дело-то :) а ваши исправления на первый взгляд правильные, если исправите - я ПР в доки закину.

**Comment by AgelxNash** [comment]
@Pathologic по данному тикету вопрос решен? Или планируешь переделать как и предложил?

**Comment by Pathologic** [comment]
В общем-то, раз @Aharito убрал из документации tplId0, то и переделывать нечего, разве что можно убрать из комментариев пояснение, что нумерация начинается с нуля.
