### ISSUE TITLE
Плейсхолдеры итерации

### ISSUE THREAD

**Issue by Aharito** [AgelxNash/DocLister#241]
Снова про итерацию, теперь про **плейсхолдеры**.
В [site_content ](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L138)это [+iteration+]
В [onetable ](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/onetable.php#L97)это [+sysKey.iteration+] со значением sysKey = dl по умолчанию
В [shopkeeper ](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/shopkeeper.php#L90)это снова  [+iteration+]

Раз плейсхолдер глобальный - видимо, везде надо делать как в **onetable**, сохранив для обратной совместимости и прежнее написание [+iteration+] для site_content и shopkeeper.

Кстати, недавно был вопрос по этому поводу на modx.im

P.S. Для [+full_iteration+] в этом плане [все ок](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1019).

**Comment by AgelxNash** [comment]
Я тоже уже об этом думал. Просто так повелось, что в site_content [+iteration+] не конфликтует со стандартным набором полей. А вот в onetable это поле может конфликтовать с полем в базе. Поэтому и добавлен префикс.

**Comment by Aharito** [comment]
Я еще не разобрался достаточно тщательно в твоем коде, да и вообще в работе MODx, отсюда вопрос - а если будет несколько вызовов DL на странице, это не может привести к каким-либо конфликтам из-за одинаковых плейсхолдеров без префикса?

**Comment by AgelxNash** [comment]
Нет. это локальные плейсхолдеры, а не глобальные. Они обрабатываются 1 раз внутри шаблона в цикле.

**Comment by Aharito** [comment]
Тогда я просто отправлю ПР в доки Дмитрию с пояснениями относительно вида плейсхолдеров в разных контроллерах.

**Comment by AgelxNash** [comment]
Да, думаю так будет правильней. Да и народу кому нужен onetable - не так много. А если уж нужен - то такие люди точно поймут что от куда.
