### ISSUE TITLE
Критическое место для быстродействия DL в режиме api

### ISSUE THREAD

**Issue by Aharito** [AgelxNash/DocLister#243]
Тестировал свой сниппет DLSiblings, он основан на DL в режиме api, как DLPrevNext.

На **300** документах при некешируемом вызове сниппета время генерации страницы **около 6 сек**, что неприемлемо.

Стал разбираться, [расставил в нужных местах microtime()](https://github.com/Aharito/DLSiblings/blob/Aharito-patch-1/snippet.DLSiblings.php), похоже, что львиную долю времени занимает [замена точек на нижнее подчеркивание](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/DocLister.abstract.php#L1079) при задании **api=`1`** ???

![image](https://cloud.githubusercontent.com/assets/6253807/24673148/70069276-19a1-11e7-9b37-69f2776b3a13.png)

А при **api=`0`** время работы DL на порядок **меньше**, правда не выводятся некоторые ТВ, но удивительно что tv.h1 все равно выводится...

![image](https://cloud.githubusercontent.com/assets/6253807/24673188/a0e6c0aa-19a1-11e7-82e4-a00436594445.png)

Пока не могу понять, в чем дело, неужели замена точек столь долгая?

**Comment by AgelxNash** [comment]
api параметр заполнен не верно. Он должен быть:
 - пустой, если api отключен
 - 1, если нужны все поля
 - перечень необходимых полей

**Comment by AgelxNash** [comment]
Не поленился и поднял тестовый сайт. Действительно, в api=1 режиме, наблюдается взрывной рост времени обработки. НО! Вся проблема в том, что при api=1 мы каждый документ проходит все возможные циклы обработки данных (генерация url, формирование даты, заголовков, и т.д. и т.п.). 

Поэтому если важна скорость, то нужно четко понимать в каких вызовах [какие данные нужны.](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L224-L255) и запрашивать только их.

**Comment by Pathologic** [comment]
@Aharito попробуй вместо манипуляций с json использовать объект:
```
$modx->runSnippet('DocLister', array(
    'tpl' => '',
    'saveDLObject' => '_DL'
));
$_DL = $modx->getPlaceholder('_DL');
$docs = $_DL->docsCollection()->toArray();
```

**Comment by Aharito** [comment]
@AgelxNash 
> api параметр заполнен не верно. Он должен быть:
> 
> пустой, если api отключен
> 1, если нужны все поля
> перечень необходимых полей

Значит я неверно понял логику при разборе кода, посмотрю еще раз внимательнее.

> Поэтому если важна скорость, то нужно четко понимать в каких вызовах какие данные нужны. и запрашивать только их.

**Благодарю**, для себя поразбираюсь ради любопытства и понимания сути происходящего. Но если говорить о сниппете DLSiblings, то он делается в том числе и "для народа", а народ вряд ли будет заморачиваться анализом, какие именно данные запрашивать :)

Поэтому воспользуюсь советом @Pathologic, кстати **спасибо** за совет, я как раз хотел пощупать эти коллекции.

**P.S.** А кольцевая перелинковка действительно полезна. Даже в категории, где всего 8-ю статей, позволила вывести статьи в **ТОП-10** по низкочастотникам в регионе Россия, и это дало стабильный небольшой трафик (в основном в Гугле, ему потребовался примерно месяц на это). 

А если статей будет 100-200, тут эффект будет на порядки выше. Так что для информационных сайтов и например блогов о веб-разработке - самое то :)

**Comment by Aharito** [comment]
@AgelxNash @Pathologic 
Как и говорил, продолжаю тестить режим api.

Ещё один вопрос: когда я задаю **&api=\`1\`**, то как я говорил, выводится всё что нужно, но первая генерация вывода DL занимает около **6 сек** для 300 ресурсов.

Если же я указываю **&api=\`id,pagetitle,tv.h1,tv.article_intro_img\`**, то генерация вывода DL занимает всего **0.395 сек**, а это уже гуд.

 Но при этом **[+tv_h1+]** выводится, а **[+tv_article_intro_img+]** - нет. В списке tvList этот ТВ article_intro_img у меня **есть**, и как я написал, при &api=\`1\` он **выводится**. Его отличие от ТВ h1 в том, что он дополнительно обрабатывается в **prepare**. 

Кстати, такая же история с **экстендером** **e** и с плейсхолдером **[+url+]**.

Какие еще данные надо указывать для экстендера е, для prepare-параметров, для [+url+]?

На код-то @AgelxNash мне ссылку дал, но я пока недоразобрался :)

**Comment by AgelxNash** [comment]
Вызов в студию в месте с prepare

**Comment by Pathologic** [comment]
В &api не нужно указывать tv.

**Comment by Aharito** [comment]
> В &api не нужно указывать tv.

Но ведь **tv_h1** - то выводится...

Убрал префикс, сделал **&api=\`id,pagetitle,h1,article_intro_img\`** - ТВ вообще не выводятся.

Вызов:
```php
[!DLSiblings?
   &idType=`parents`
   &parents=`[*parent*]`

   &thumbSnippet=`sgThumb`
   &thumbOptions=`{"tv.article_intro_img":{"medium":"700x400"}}`

   &ownerTPL=`@CODE:<div class="row latest-news inline-showcase">[+wrap+]</div><hr>`                              
   &tpl=`@CODE:<div class="column col-1-1-2-4-4 margin-bottom-30">
   <div class="article-announce-img margin-bottom-10">
      <img class="img-responsive" src="[+tv_article_intro_img_medium+]" alt="[+e_title+] | [(cfg_company_brand_name)]">            
   </div>

   <div class="article-announce-content">
      <div class="article-announce-header">
         <a href="[+url+]">[+tv_h1+]</a>
      </div>
   </div>

   <a href="[+url+]" class="wrapper-link"></a>
   </div>`

   &Qty=`2`
   &tvList=`h1,article_intro_img`
   &prepare=`FastImageTVPreviews`
   &api=`id,pagetitle,menutitle,tv.h1,tv.article_intro_img`
!]
```
prepare **FastImageTVPreviews**:
```php
<?php
//[[DocLister? &thumbSnippet=`sgThumb` &thumbOptions=`{"tv.image":{"small":"250x250","medium":"500x500"}}` &tpl=`@CODE:[+tv.image+] [+tv.image.small+] [+tv.image.medium+]`]]
//<img src="[[snippet? &input=`[*image*]` &options=`250x250`]]">
if (isset($_DocLister) && is_object($_DocLister)) {
   $thumbs = json_decode($_DocLister->getCFGDef('thumbOptions','{}'),true);
   foreach ($thumbs as $key=>$value) {
      if (isset($data[$key])) {
         foreach ($value as $name => $options) {
            $data[$key.'.'.$name] = $modx->runSnippet($_DocLister->getCFGDef('thumbSnippet','sgThumb'),array('input'=>$data[$key],'options'=>$options));
         }
      }
   }
   return $data;
} else {
   return $modx->runSnippet('sgThumb', array('input'=>$input,'options'=>$options));
}
```
### Результат:

![image](https://cloud.githubusercontent.com/assets/6253807/24703819/1ccc3a50-1a2f-11e7-8c44-4ae9dfe2d621.png)

Тот же вызов, но с &api=`1`, результат:

![image](https://cloud.githubusercontent.com/assets/6253807/24703870/67c19460-1a2f-11e7-8ae6-fa71126ac0fe.png)

**Comment by Pathologic** [comment]
Я про то, что в &api указываются только поля таблицы, а tv указываются в &tvList.

**Comment by Pathologic** [comment]
В thumbOptions нужно tv_article_intro_img

**Comment by Aharito** [comment]
С выводом ТВ **разобрался**, в принципе это логично, мог бы и сразу догадаться. В параметр **&api** нужно записывать не "исходный" ТВ, а те данные, что формируются в массиве $data через **prepare** для вывода.

В моем случае исходный ТВ - это **$data['tv.article_intro_img'**],  а для вывода в prepare формируется **$data['tv.article_intro_img.meduim']**, вот он-то и отсутствовал в списке &api. Как только я сделал **&api=`id,tv.h1,tv.article_intro_img.medium`**, картинки сразу вывелись, и время Ок.

![image](https://cloud.githubusercontent.com/assets/6253807/24710630/ef44afd6-1a47-11e7-8177-5a93e716e2b4.png)

**Comment by Aharito** [comment]
Если упростить вызов так:
```
[!DocLister?
   &idType=`documents`
   &documents=`370`
   &api=`menutitle,pagetitle`
!]
```

То в выводе видим
`{ "370": { "pagetitle": "\u0421\u0440\u0430\u0432\u043d\u0435\u043d\u0438\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u043e\u0432 \u043f\u043e \u0433. \u041a\u0440\u0430\u0441\u043d\u043e\u0433\u043e\u0440\u0441\u043a - 42", "menutitle": "" } }`

То есть присутствует **pagetitle**, есть пустой **menutitle**, а вот **title нету**, хотя [здесь ](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L232-L234)все должно выполняться. Возможно, [здесь ](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L260)что-то, но в это пока не врубаюсь.

**Comment by Aharito** [comment]
По **[+url+]** [проверяется наличие](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L235) поля **content** и поля **type** в выборке, но обработка content занимает время.

![image](https://cloud.githubusercontent.com/assets/6253807/24713587/5a452c5e-1a50-11e7-82f2-94fa26b46743.png)

![image](https://cloud.githubusercontent.com/assets/6253807/24713680/8e660bde-1a50-11e7-984c-739c9bd21184.png)

Разница в **4 секунды**!

Есть 2 выхода: заменить [+url+] на [~[+id+]~] или [переписать это](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L235-L244).

Хотя, при таком вызове
```
[!DocLister?
   &idType=`documents`
   &documents=`370`
   &api=`id,content,type`
!]
```
данные для URL в результирующей JSON-строке все равно **не появились**, где-то еще момент какой-то есть.

**Comment by dmi3yy** [comment]
Да только если у нас документ ссылка то теряем URL что не логично

**Comment by Aharito** [comment]
> Да только если у нас документ ссылка то теряем URL что не логично

Это по поводу этого?

> заменить `[+url+]` на `[~[+id+]~]`

Я имел в виду заменить у себя **в шаблоне**, у меня веб-ссылок нету, поэтому я коммент свой подредактировал так:

> заменить **в шаблоне** `[+url+]` на `[~[+id+]~]`

**Comment by Aharito** [comment]
А для общего случая я как раз [PR отправил](https://github.com/AgelxNash/DocLister/pull/245)

**Comment by Pathologic** [comment]
@Aharito может проще сначала получить id документов, а потом уже вызвать с ними DocLister? Тогда вроде как и не понадобится гонять 300 документов.

**Comment by AgelxNash** [comment]
@Pathologic, поддерживаю. Можно даже запустить DL первый раз получив только ID. Сформировать нужный список документов и потом еще раз вызвать DL уже с оставшимися полями.

**Comment by Aharito** [comment]
@AgelxNash @Pathologic 

Понимаю, но из интереса ковырялся, не хотелось 2 раза DL вызывать, это слишком тривиально.

А все-таки, почему ни [+title+], ни [+url+] не формируются в любом случае, кроме &api=\`1\`?

**Comment by AgelxNash** [comment]
@Aharito потом, что там ошибка о которой [писал тут](https://github.com/AgelxNash/DocLister/pull/245#issuecomment-291922743)
```php
 in_array(array('content', 'type'), $fields)
```

**Comment by Aharito** [comment]
Даже если я у себя меняю [эту строку](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/site_content.php#L235)
`if ((bool)$this->getCFGDef('makeUrl', 1) && (array('1') == $fields || in_array(array('content', 'type'),
            $fields))
 ) {`

на строку

`if (true) {`
то всё равно ничего не меняется.

**Comment by AgelxNash** [comment]
&api=`reference,type,content,id`

**Comment by AgelxNash** [comment]
@Aharito по сабжу последнего вопроса https://github.com/AgelxNash/DocLister/issues/171

**Comment by Aharito** [comment]
> &api=reference,type,content,id

Честно говоря, это вообще не понял - зачем там **reference**.  Ну и все равно не работает.
