### ISSUE TITLE
APIhelpers::_getEnv

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#244]
Этот метод появился лишь для того, чтобы php 5.2 не ругался на замыкания в APIhelpers::getUserIP(). Сейчас PHP 5.2 поддерживать нет смысла и можно было бы отказаться от лишнего метода. Но, возможно имеет смысл его не удалять, а сделать публичным, чтобы в разных участках приложения иметь возможность получать данные?

**Comment by Pathologic** [comment]
Я за публичный метод.
