### ISSUE TITLE
В onetable - if ($sanitarInIDs != "''") 2 раза подряд

### ISSUE THREAD

**Issue by Smileroff** [AgelxNash/DocLister#249]
Случайно заметил [тут](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/core/controller/onetable.php#L312).
`            if ($sanitarInIDs != "''") {
                if ($sanitarInIDs != "''") {`
Видимо осталось после чего то.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/3a0e38913742fe05b9f81fb52d9c51d2555bd5fc
