### ISSUE TITLE
Какая-то фигня с gitignore

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#260]
https://github.com/AgelxNash/DocLister/commit/88e5ae95e635ab9ec45a12db3df4b8abd8059fcc

**Comment by AgelxNash** [comment]
После изменения gitignore необходимо удалить файлы из репозитория. https://ru.stackoverflow.com/questions/432432/%D0%9D%D0%B5-%D0%B8%D0%B3%D0%BD%D0%BE%D1%80%D0%B8%D1%80%D1%83%D1%8E%D1%82%D1%81%D1%8F-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D0%B2-gitignore

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/blob/d50b589f2f778a3dc320c71e0e9d2ec0b25ad6ed/.gitignore - если этот вернуть, ничего ж не сломается?

**Comment by AgelxNash** [comment]
По идее нет. Но нужно проверить вдруг лишние файлы добавятся
