### ISSUE TITLE
Не работает параметр &depth, попытка дебага сваливает сайт в MODX Parse Error

### ISSUE THREAD

**Issue by sunhaim** [AgelxNash/DocLister#265]
Вызов:
```
[[DocLister? &parents=`5` &depth=`1` &tpl=`sale_projects_tpl` &ownerTPL=`sale_projects_wrap` &display=`2` &tvList=`thumb,address`]]
```
Требуется вывести только документы первого уровня, но выводятся самые нижние.

Когда добавляю параметр &debug=`1`, вываливается ошибка:

<img src="https://monosnap.com/file/exJl9CcRTz9yzCT1Is4GIhdnFj5yiZ.png">
<img src="https://monosnap.com/file/BYyM8i8sa4sgUCS8hXMZUQqnBkQfNm.png">

**Comment by sunhaim** [comment]
Разобрался с параметром &depth, нужно ставить 0, чтобы не выводить дочерние документы.

**Comment by Pathologic** [comment]
Версия какая?

**Comment by sunhaim** [comment]
MODX EVO Custom 1.2.1-d9.1.7
DocLister 2.3.1

**Comment by Pathologic** [comment]
Актуальная версия  - 2.3.4.
