### ISSUE TITLE
Регистрозависимость во время поиска пользователя

### ISSUE THREAD

**Issue by Ser1ous** [AgelxNash/DocLister#281]
У меня тут возникла проблема, когда настраиваю в формлистере авторизацию через email, то всё упирается в регистрозависимость email-а, что как бы странно.
Я нашёл, что во время поиска пользователя идёт WHERE BINARY, в чём принципиальность такого WHERE? Учитывая что идёт поиск по атрибутам пользователя.
https://github.com/AgelxNash/DocLister/blob/master/assets/lib/MODxAPI/modUsers.php#L119

**Comment by Pathologic** [comment]
Да, странно как-то. Единственная причина, которая приходит в голову - WHERE BINARY быстрее.

**Comment by AgelxNash** [comment]
Если ваш сниппет регистрации и авторизации передает строки как есть без преобразования, то гипотетически возможна регистрация нескольких пользователей с одним и тем же логином/почтой, только в разных регистрах. Поэтому в сниппетах регистрации/авторизации поле логин должно быть либо регистрозависимым и тут как раз BINARY, либо принудительно приводиться в нижний/верхний регистр, чтобы не спотыкаться об BINARY.
