### ISSUE TITLE
&outputSeparator	Необязательная строка для разделения результатов работы.

### ISSUE THREAD

**Issue by nuclear4547** [AgelxNash/DocLister#290]
в Revo pdotools есть такой параметр
&outputSeparator | Необязательная строка для разделения результатов работы.
было бы замечательно добавить аналог в DL

**Comment by Pathologic** [comment]
А для чего это?

**Comment by AgelxNash** [comment]
Я так понимаю добавить допустим <hr /> после каждого элемента, кроме последнего (так же как делает это функция implode). Но сейчас этот же самый функционал можно реализовать через tpl + tplLast

**Comment by nuclear4547** [comment]
да, это аналог implode.
согласен, данный функционал можно реализовать как с помощью tpl + tplLast, так и с помощью помещения в шаблон сниппета IF с проверкой итерации
но в первом случае если надо внести правку в шаблон, то править надо будет оба шаблона, а использование сниппета как минимум не эстетично, не говоря даже о том, что приходиться отказываться от @CODE, а также  дополнительный запуск сниппета
