### ISSUE TITLE
DLSitemap dateformat

### ISSUE THREAD

**Issue by fourroses666** [AgelxNash/DocLister#291]
```
[[DLSitemap? 
&filters=`content:template:notin:0` 
&dateFormat=`%Y-%m-%d` 
&dateSource=`pub_date`
]]
```
Starting to convert old plugins to new ones.
And since we don't have a forum yet I'm asking here.

How can I change this dateformat? The above doesn't work for me, no changes.
`<lastmod>2018-01-26T17:45:01+01:00</lastmod>`

Need to have:
`<lastmod>2018-01-26</lastmod>`

I can change the JSON file (assets/snippets/DocLister/config/core/sitemap.json) and change `[+date+]` to: ```[+date:date=`%d-%m-%Y`+]```

But it gets overwritten when updating DocLister.

-------

snippet.DLSitemap.php you can change http to https:
`if (!isset($schema)) $schema = "https://www.sitemaps.org/schemas/sitemap/0.9";`

**Comment by fourroses666** [comment]
```
[[DLSitemap? &filters=`content:template:notin:0` &tpl=`@CODE:<url>
	<loc>[+e.url+]</loc>
	<lastmod>[+date:date=`%d-%m-%Y`+]</lastmod>
	<changefreq>[+update+]</changefreq>
	<priority>[+priority+]</priority>
</url>`]]
```

This works but would it be a good idea to add it to the json?

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/6db444fc19d7352e310c0d1cc34eee3139c77a16
https://github.com/AgelxNash/DocLister/commit/ee535800101bfb709fe566a275996dff44107feb

**Comment by Pathologic** [comment]
You can create your own json and load it with &config.

**Comment by fourroses666** [comment]
Thanks Pat, but its not working for me.

The result is still;
`<lastmod>01-01-1970</lastmod>` when using:  `<lastmod>[+date:date=`%d-%m-%Y`+]</lastmod>`
`<lastmod>2018-02-12T10:13:53+0100</lastmod>` when using: `<lastmod>[+date+]</lastmod>`

BTW updating DocLister gave this result: _(bug in extras or server setting?)_
`[{"result":"false","error":"Error:Download: /var/www/d12010001/dfgdsfg.com/www/assets/modules/store/core.phpline 149): Could not open the file!"}]`

(Did the "handmade" update 6db444f.)

**Comment by Pathologic** [comment]
No, DocLister has nothing to do with Extras module issues (: I've checked dateFormat parameter and it works as expected.
