### ISSUE TITLE
Перестал работать phx

### ISSUE THREAD

**Issue by Grinyaha** [AgelxNash/DocLister#297]
Не работает, или работает криво phx в чанках DL. Вернул старый класс и все заработало.

**Comment by Grinyaha** [comment]
А версия движка какая? у меня 1.5 beta.

**Comment by Pathologic** [comment]
Такая же.

**Comment by Grinyaha** [comment]
Причем у меня и плагин phx тоже глючить начал на 1.5 beta.

**Comment by Pathologic** [comment]
Или пиши, как ошибку получить, или закрывай issue :smile_cat:
