### ISSUE TITLE
Отказ от поддержки PHP 5

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#301]
PHP 5.6 уже официально не поддерживаются. Внедряются только исправления безопасности до 31 декабря 2018. Даже исправления безопасности в PHP 7.0 будут внедряться только до 3 декабря 2018 года.

Тот же PHPUnit версии 5 прекратили поддерживать еще со 2 февраля 2018 года. А в DocLister тесты еще на версии PHPUnit 4.2.

Все адекватные хостинги уже давно имеют опцию переключения версии PHP на лету. Может быть есть смысл стимулировать людей обновляться хотя бы дополнением?

**Comment by Pathologic** [comment]
Пока что основной затык в нашем дорогом зарубежном сообществе, которое вовсю использует древние дополнения (:

**Comment by dmi3yy** [comment]
Я считаю что логично держать 5.6 до 31.12.2018  но опять же зависит все от потребностей если есть что то важное что работает на 7.0 и не работает на 5.6 и даст преимущества то да можно и отказываться от 5.6 но я пока не вижу чего б такого сделать что б было нужно и не работало на 5.6

**Comment by AgelxNash** [comment]
@dmi3yy это лишь симуляция для обновления до современного программного обеспечения. Я не вижу ни одной внятной причины почему нужно еще сидеть на 5.6 или ниже, если всегда есть возможность переключиться на 7.0 и выше.

На данный момент почти все современные хостеры позволяют в один клик сменить версию. Ну а топики про то, что [движок пытаются завести на php 5.2](http://modx.im/blog/questions/4091.html) так вообще умиляют.

Вот явные преимущества (лично я уже пользуюсь) которые мы поимеем переходя на

[PHP 5.4](https://secure.php.net/manual/ru/migration54.new-features.php)
========
- Трейты https://secure.php.net/manual/ru/language.oop5.traits.php
- Поддержка $this в замыканиях

[PHP 5.5](https://secure.php.net/manual/ru/migration55.new-features.php)
========
- Разрешение имен класса с помощью ::class
- Новое API хеширования паролей
- Использование в функции preg_replace() модификатора /e объявлено устаревшим
- Расширение ext/mysql признано устаревшим

[PHP 5.6](https://secure.php.net/manual/ru/migration56.new-features.php)
========
- Константу можно определить как массив или даже скалярное выражение
- Функции с переменным количеством аргументов
- Загрузка функций и констант в namespace через use оператор
- Поддержка загрузки файлов размером более 2 ГБ
- Улучшенная поддержка SSL/TLS
- [Установка пароля для ZIP архивов](https://secure.php.net/manual/ru/ziparchive.setpassword.php)

[PHP 7.0](https://secure.php.net/manual/ru/migration70.incompatible.php)
========
- Функции exec(), system() и passthru() теперь защищены от NULL-байта.
- Объявления скалярных типов в аргументах функций
- Объявления возвращаемых значений из функции
- Определение констант массивов с помощью define()

Добавим сюда сравнения в скорости и вопрос как бы о явных преимуществах отпадает сам собой.

**Comment by dmi3yy** [comment]
Дык я сам только на 7.0 уже работаю ибо реально шустрее:) 

Но дык у нас и так не очень большое сообщество ну и скоро и так и так отвалиться php 5 

к примеру вот я не собираюсь Ditto обновлять под 7.2 а с ним eForm и JotX(хотя тут надо написать замену)   

Так что как по мне пока работает пусть работает а вот если запулить версию 2.0 то там да можно смело писать что только 7.0+ без проблем вообще 

Ну и по факту пол года ничего не решают а вот зимой я в любом случае просто насильно поставлю минимальные требования на 7.0 ибо 5.6 больше не поддерживается а мы за безопасность :) и тогда шансов возразить не будет или пусть возражают создателям php

**Comment by AgelxNash** [comment]
https://habrahabr.ru/company/plesk/blog/352408/

**Comment by AgelxNash** [comment]
Ветка develop будет адаптирована для Evolution 2.0 и соответственно минимально поддерживаемая версия будет уже PHP 7.1.3
