### ISSUE TITLE
DocLister doesn't render TVs in EVO 1.4.2

### ISSUE THREAD

**Issue by Pathologic** [AgelxNash/DocLister#302]
One of my sites have problem with DocLister after upgrade to 1.4.2.
Looks like DL is ignoring renderTV parameter.
In 1.4.1 date TVs was rendered as "1522312740" but in 1.4.2 it is like "2018-03-12". Same problem with other TVs like radio with delimeted list widget.

I have uploaded DocLister from EVO 1.4.1 to the upgraded site and everything went back to normal.

**Comment by pmfx** [comment]
It doesn't render TVs. Was fine in EVO 1.4.1.
Just checked other 1.4.2 site on different server and there is the same problem.
All OK after downgrading DocLister to the version from EVO 1.4.1

## In snippet:

```
$params['tvList']   = 'competition_date,competition_date_end,competition_disciplines';
$params['renderTV'] = 'competition_date,competition_date_end,competition_disciplines';
```

## TVs:

![screenshot_1](https://user-images.githubusercontent.com/10888055/37936874-80b0e30a-3157-11e8-9970-d591541c963b.png)

![screenshot_2](https://user-images.githubusercontent.com/10888055/37936881-863bec02-3157-11e8-9616-8fce425a42fe.png)

## Chunk:

![screenshot_3](https://user-images.githubusercontent.com/10888055/37936885-8bdc320c-3157-11e8-963e-6cebb68d2325.png)

**Comment by Pathologic** [comment]
I'll fix it tomorrow.

**Comment by pmfx** [comment]
Thanks
