### ISSUE TITLE
DLSitemap: FP: Скрывать разделы по ID

### ISSUE THREAD

**Issue by sashabeep** [AgelxNash/DocLister#306]
Нет встроенного параметра, отвечающего за исключение разделов из карты сайта

**Comment by Pathologic** [comment]
filters, addWhereList

**Comment by sashabeep** [comment]
@Pathologic слишком сложный фильтр для раздела с подразделами с разными шаблонами
![2018-04-23 11 55 01](https://user-images.githubusercontent.com/5689796/39116458-2eade3ea-46ed-11e8-9dce-edb93566a70f.png)

**Comment by Pathologic** [comment]
idtype=parents, addWhereFolder

**Comment by sashabeep** [comment]
@Pathologic addWhereFolder похоже, то, что нужно, но параметр не описан в документации
