### ISSUE TITLE
Перестал работать currentDepth в DLBuildMenu

### ISSUE THREAD

**Issue by toha-proud** [AgelxNash/DocLister#314]
В TplSubOwner перестал работать плейсхолдер [+dl.currentDepth+]

**Comment by Pathologic** [comment]
А вызов как выглядит?

**Comment by toha-proud** [comment]
Вызов вот
[[DLBuildMenu? 
						&parents=`2`
						&maxDepth=`5` 
						&display=`8` 
						&TplMainOwner=`@CODE: <nav><ul>[+dl.wrap+]</ul></nav>` 
						&TplDepth1=`TplDepth1`
						&TplDepth2=`TplDepth2`
						&TplDepth3=`TplDepth3`
						&tvPrefix=``
						&tvList=`pagetitle_en,pagetitle_ua,pagetitle_ru,image,menudocs`
						&addWhereList=`isfolder=1`
						]]
TplSubOwner родной. В нем как раз [+dl.currentDepth+] ни чего не возвращает. Откатил DocLister до 2.1.0 там нормально работает

**Comment by Pathologic** [comment]
Исправил, но вообще этот сниппет deprecated.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/473983e16f7b9e8ba3f33c2c723ca4a750d8747d
