### ISSUE TITLE
экранирование

### ISSUE THREAD

**Issue by gadev** [AgelxNash/DocLister#322]
https://github.com/AgelxNash/DocLister/blob/66ea0cb335bb84df660652b8eef84e7a13285146/assets/snippets/DocLister/core/DocLister.abstract.php#L1674

тут зачем-то убирается экранирование, которое делается в функции build_sql_where

как результат, при поиске **D'Alco** (filters – tv:brand:eq:D'Alco) мы получаем sql-ошибку

**Comment by AgelxNash** [comment]
https://github.com/AgelxNash/DocLister/commit/0de5c08409a942a8e8f2eb18b6256c61b27c0391

**Comment by AgelxNash** [comment]
#276
