### ISSUE TITLE
Http 500 error on Doclister with phpthumb page.

### ISSUE THREAD

**Issue by mgzawlinoo** [AgelxNash/DocLister#325]
Hi,
I have Http 500 error on my webpage (use Doclister with phpthumb + prepare snippet).
Next day my server show that error in log and can't access that web page .
[mpm_prefork:error] [pid 30660] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
But other web pages can access include ( Doclister +no phpthumb) .

That error not show always, I can access that web page (use Doclister with phpthumb + prepare snippet) and next two or three days, that web page show " currently unable to handle this request HTTP ERROR 500 " 

No php error in error log.

And I found another strange things on my sites .
Eg . I have two web sites (A and B)
When Site A have http 500 error on Doclister + phpthumb page.
If I clear cache on Site B.
That Http 500 error on Site A is clear.
I don't know why.

And That error can also solve by restarting my apache server.

**Comment by mgzawlinoo** [comment]
strange, I found another strange things on my sites .
Eg . I have two web sites (A and B)
When Site A have http 500 error on Doclister use page.
If I clear cache on Site B.
That Http 500 error on Site A is clear.
I don't know why.

**Comment by AgelxNash** [comment]
I think your call has a lot of documents on the page. And each of the documents contains a picture for which there is no preview. When you open this page, try to create all the previews at once and you get a limit MaxRequestWorkers.

Try limiting output with the ```display``` option. When the previews are created - try incrementing the value.
