### ISSUE TITLE
Подгрузка лексиконов

### ISSUE THREAD

**Issue by mnoskov** [AgelxNash/DocLister#326]
https://github.com/AgelxNash/DocLister/blob/66ea0cb335bb84df660652b8eef84e7a13285146/assets/snippets/DocLister/core/DocLister.abstract.php#L782-L793

Это похоже на ошибку - проверяется наличие одного файла, а подключается другой.

Также, можно ли добавить подгрузку лексиконов из произвольной папки?

**Comment by Pathologic** [comment]
Я собирался переделать лексиконы, чтобы было как в формлистере.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/c952da7955d6f6fb398375780d64dbcddedd1619
