### ISSUE TITLE
Недоступен плейсхолдер pages в шаблоне ownerTPL

### ISSUE THREAD

**Issue by mnoskov** [AgelxNash/DocLister#329]
С некоторых пор стал недоступен плейсхолдер pages, если его включать в шаблон ownerTPL. Снаружи работает, а в обертке - нет.

Рабочий вызов:
```php
[[DocLister?
    &id=`list`
    &display=`1`
    &paginate=`pages`
]]

[+list.pages+]
```

Нерабочий вызов:
```php
[[DocLister?
    &id=`list`
    &display=`1`
    &paginate=`pages`
    &ownerTPL=`[+dl.wrap+] [+list.pages+]`
]]
```

Раньше нерабочий вызов также работал.

Evolution v1.4.5
DocLister v2.3.15

**Comment by Pathologic** [comment]
Это исправлено. https://github.com/AgelxNash/DocLister/commit/3deb4d06ab7b93e00c3d520806893a626047c177
