### ISSUE TITLE
Предложения по новым функциям

### ISSUE THREAD

**Issue by Rising13** [AgelxNash/DocLister#336]
предлагаю добавить некоторые полезные параметры и плейсхолдеры:
1. Разделитель (separator), который будет выводить значение, указанное в параметре "separator" между результатами запроса (шаблоны, указанные в параметре tpl).
2. Плейсхолдер (например [+doc_count+]) с выводом количества результатов запроса, работающий без задействования пагинации (желательно, чтоб отрабатывал и в шаблоне одного результата). 
3. Плейсхолдеры [+is_first+] и [+is_last+], которые будут выводить значение "1" для первого и последнего элементов соответственно

**Comment by AgelxNash** [comment]
Для первого пункта используйте параметр ```outputSeparator```
