### ISSUE TITLE
EVO 2.0.0 - Проблемы с @B_FILE

### ISSUE THREAD

**Issue by cgehuzi** [AgelxNash/DocLister#338]
**Версия EVO**: 2.0.0-alpha
**Версия PHP**: PHP-7.2
**Версия Mysq**l:  MySQL-5.6

**Описание ошибки**:

Вызов DocLister с `@B_CODE:` отрабатывает без ошибок:
```
{!! $modx->runSnippet('DocLister',[
    'parents' => '2',
    'tpl' => '@B_CODE:{{ $data["pagetitle"] }}'
]) !!}
```

Вызов DocLister с `@B_FILE:` не выводит ничего:
```
{!! $modx->runSnippet('DocLister',[
    'parents' => '2',
    'tpl' => '@B_FILE:partials/doc-tpl'
]) !!}
```

Файл `views/partials/doc-tpl.blade.php` создан и содержит код:
```
{{ $data["pagetitle"] }}
```

Проверил несколько вариантов записи:
```
'tpl' => '@B_FILE:partials/doc-tpl.blade'
'tpl' => '@B_FILE:partials/doc-tpl.blade.php'
'tpl' => '@B_FILE:/views/partials/doc-tpl'
'tpl' => '@B_FILE:/views/partials/doc-tpl.blade'
'tpl' => '@B_FILE:/views/partials/doc-tpl.blade.php'
```
Результат тот же.

**Comment by AgelxNash** [comment]
Файлы должны находиться в папке [assets/templates/](https://github.com/AgelxNash/DocLister/blob/master/assets/snippets/DocLister/lib/DLTemplate.class.php#L22)
