### ISSUE TITLE
Приведение типов при фильтрации по TV параметрам

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#34]

**Comment by ognivo777** [comment]
Добрый день! В названии тудушки указана фильтрация, а реализовано приведение типов только в сортировке. Судя по всему фильтрации по датам, к примеру, всё ещё нет.. Тогда непонятно почему закрыта таска..

**Comment by AgelxNash** [comment]
MySQL использует не явное приведение типов. Для примера, выбора две выборки вроде бы одинаковые, но вернут абсолютно разный результат:
```sql
SELECT * FROM table WHERE string_field > 10.2
SELECT * FROM table WHERE string_field > '10.2'
```
Что же касается приведения типа для фильтрации по датам с приведением типов, то на мой взгляд слишком много гемороя ради сомнительного профита, т.к. на выходе получаем слишком ресурсоемкие запросы, которые все-равно придется переделывать как только сайт начнут посещать люди. При этом ради такого удовольствия придется перелопатить кучу кода в ядре DocLister'a.

Так что если уж нужна фильтрация с приведением типов, То рекомендую написать плагин на событии OnDocFormSave, перехватывать значения сохраняемых полей. преобразовывать в нужный вам формат и сохранять в поле с нужным типом. Добавлять поля в таблицу site_content вам никто не запрещает.

P.S. Для сортировки по ТВ параметрам вида datetime, реализация заложена в контроллере site_content. Для остальных частных случаев всегда можно расширить контроллер и добавить свое приведение типа. Если вдруг я пропустил какой-то другой популярный тип преобразования, то пожалуйста, исправьте меня PullRequest'ом.
