### ISSUE TITLE
Undefined index: id

### ISSUE THREAD

**Issue by 64j** [AgelxNash/DocLister#341]
PHP Minor Problem
Error : Undefined index: id
assets/snippets/DocLister/core/controller/site_content_menu.php
Line: 392
$id = $data['id'];

Ошибка вываливается только при параметре debug=1

**Comment by AgelxNash** [comment]
Обернуть переменную в isset не проблема. Но по коду очень много чего зависит от этих данных, поэтому если там undefined index, то должно многое и не работать.
Какой полный вызов и структура дерева?

**Comment by Pathologic** [comment]
Из-за параметра selectFields может такое случиться.
