### ISSUE TITLE
DocLister - exclude doc ID in &filter doesn't work

### ISSUE THREAD

**Issue by modwebpl** [AgelxNash/DocLister#343]
Hello, i want to show news (in sidebar) excluded the current document ( I have read this DEV DOC: https://github.com/Nicola1971/Ditto-to-DocLister-Reference-Tables )

In Ditto works: &filter="id,[*id*],2"
In DocLister this doesn't work: &filters="AND(id:isno[*id*])"

How can I solve this ?

**Comment by pmfx** [comment]
```
&filters=`AND(content:id:isnot:123)`
```
also try this:
```
&addWhereList=`c.id!=123`
```
More details and examples: https://github.com/AgelxNash/DocLister/issues/333

**Comment by modwebpl** [comment]
Gracias!
