### ISSUE TITLE
Ошибка при вызове $modx->runSnippet('DLMenu') в Blade - ошибка Cannot declare class DLTemplate

### ISSUE THREAD

**Issue by AntonFix** [AgelxNash/DocLister#346]
Привет.
При вызове DLMenu:
`@section('header')
    {!! $modx->runSnippet('DLMenu',[
    'parents'=>'0',
    'maxDepth'=>'2',
    'outerTpl'=>'@CODE:<ul[+classes+]>[+wrap+]</ul>',
    'rowTpl'=>'@CODE:<li[+classes+]><a class="nav-link" href="[+url+]">[+title+]</a></li>',
    'parentRowTpl'=>'@CODE:<li[+classes+]><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">[+title+]</a>[+wrap+]</li>',
    'innerTpl'=>'@CODE:<div[+classes+] aria-labelledby="navbarDropdown">[+wrap+]</div>',
    'innerRowTpl'=>'@CODE:<a class="dropdown-item" href="[+url+]">[+title+]</a>',
    'hereClass'=>'active',
    'rowClass'=>'nav-item',
    'parentClass'=>'dropdown',
    'outerClass'=>'navbar-nav mr-auto',
    'innerClass'=>'dropdown-menu'
    ])
!!}
@show`

Получаю вот такую ошибку:
> Cannot declare class DLTemplate, because the name is already in use

Не понимаю где он уже успел объявиться.

Все остальные сниппеты и теги работают корректно.

**Comment by Pathologic** [comment]
Это в 2.0?

**Comment by AntonFix** [comment]
> Это в 2.0?

Да.

**Comment by Dmi3yy** [comment]
Исправили уже
