### ISSUE TITLE
addWhereList с выборкой по tv с типом ввода date не работает, если нет параметра &orderBy

### ISSUE THREAD

**Issue by lazar2038** [AgelxNash/DocLister#348]
!!! Не связано с #236 !!!

Вот так работает:
https://monosnap.com/file/1EKyGxrkn5qDyWiHXPR5dh2O3oDGwY

А без строки orderBy не работает.

**Comment by Pathologic** [comment]
Оно и не должно работать, потому что addWhereList подставляется в запрос как есть.
