### ISSUE TITLE
Пагинация не учитывает документы, отфильтрованные через prepare

### ISSUE THREAD

**Issue by Temus** [AgelxNash/DocLister#352]
Создаются пустые страницы по изначальному числу неотфильтованных документов.

**Comment by nuclear4547** [comment]
вроде как prepare нигде и не заявлялся для фильтрации набора (документов).

**Comment by AgelxNash** [comment]
@nuclear4547 такая возможность была предусмотрена http://modx.im/blog/questions/3581.html
Но использование фильтрации на уровне prepare несовместимо с пагинацией как хочет использовать @Temus
