### ISSUE TITLE
краш после обновления

### ISSUE THREAD

**Issue by warchild1** [AgelxNash/DocLister#364]
обновил эво с 1.4.10 на 1.4.11, соответственно, доклистер с 2.5.0 на 2.5.2. Крашится с такой ошибкой:

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /home/p/premiesa/site.ru/public_html/assets/snippets/DocLister/core/DocLister.abstract.php
Line | 1516
Source | if ($limit < ($total - $limit)) {
Current Snippet | DocLister

Backtrace
--
DocumentParser->executeParser()index.php on line 139
DocumentParser->prepareResponse()manager/includes/document.parser.class.inc.php on line 2863
DocumentParser->outputContent()manager/includes/document.parser.class.inc.php on line 2987
DocumentParser->parseDocumentSource(string $var1)manager/includes/document.parser.class.inc.php on line 917
DocumentParser->evalSnippets(string $var1)manager/includes/document.parser.class.inc.php on line 2718
DocumentParser->_get_snip_result(string $var1)manager/includes/document.parser.class.inc.php on line 2028
DocumentParser->evalSnippet(string $var1, array $var2)manager/includes/document.parser.class.inc.php on line 2116
eval()manager/includes/document.parser.class.inc.php on line 1965
require(string $var1)manager/includes/document.parser.class.inc.php(1965) : eval()'d code on line 1
site_contentDocLister->getDocs()assets/snippets/DocLister/snippet.DocLister.php on line 45
site_contentDocLister->getChildrenList()assets/snippets/DocLister/core/controller/site_content.php on line 87
DocLister->LimitSQL('all')assets/snippets/DocLister/core/controller/site_content.php on line 573

**Comment by sashabeep** [comment]
Рекомендую заглянуть в основную документацию и сравнить свой вызов с возможными значениями параметров, которые вы указываете http://docs.evo.im/04_extras/doclister/parameters.html
