### ISSUE TITLE
Вывод данных из tv

### ISSUE THREAD

**Issue by ultraviolet** [AgelxNash/DocLister#369]
Версия 1.4. ТВ h1: `[*pagetitle*]`

Вызов (*не* на родителе):
```
[[DocLister?
&idType=`parents`
&parents=`X`
&orderBy=`c.pub_date DESC`
&tvList=`h1`
&tpl=`@CODE:[+tv.h1+]`
]]
```
Подставляется значение pagetitle документа, где производится вызов Доклистера. 

Пробую ещё так:
```
[[DocLister?
&idType=`parents`
&parents=`X`
&orderBy=`c.pub_date DESC`
&tvList=`h1`
&tpl=`@CODE:[+tv.h1+]`
&prepare=`prepH1`
]]
```
Сниппет prepH1:
```
<?php
$h1 = $modx->runSnippet('DocInfo', array(
  'docid' => $data['id'],
  'field' => 'h1'
));
$data['tv.h1'] = $h1;
return $data;
```
Не могу понять, почему выводит значение документа, где производится вызов. Каким образом сделать так, чтобы выводилось значение тв документа из выборки?

**Comment by Pathologic** [comment]
Использовать prepare.
