### ISSUE TITLE
Install DocLister

### ISSUE THREAD

**Issue by webkarli** [AgelxNash/DocLister#374]
I have new installed EVOLUTION 3.1.3 on a production server. DocLister cannot be installed with the module for Extras ( Package Management). 
I can still select the components (DocLister, DLMenu etc.). Then the installation aborts with this message: 
Not Found
The requested document was not found on this server.

The snippets were loaded onto the server. The snippets are not available in the backend.

PHP Version 7.3.25 
DB (MySQL) version 5.5.62 

Translated with www.DeepL.com/Translator (free version)

**Comment by mTresk** [comment]
Same

**Comment by Pathologic** [comment]
.It's Extras module issue or somethins's wrong with your server.
