### ISSUE TITLE
Display TV with Delimiter error

### ISSUE THREAD

**Issue by yanqpl** [AgelxNash/DocLister#383]
Unfortunately, there is a problem with displaying template variables in the news / search results list
I have TV call `time` with input type - checkbox, delimiter ` ,<br>` 
Input Output Values:
`Value1==Value1||Value2==Value2||Value3==Value3`

When I try to display it in the search results with `[+tv.time+]`, it unfortunately displays without the separator ie.
`Value2||Value3`

But when i display it on subpage with `[*time*]` works fine and gives a result ie.
```
Value1,
Value2
```

**Comment by Pathologic** [comment]
https://docs.evo-cms.com/en/latest/04_Extras/DocLister/01_Parameters/ - renderTv

**Comment by cimt** [comment]
Hi @Pathologic 
I have the same result!
please read here: https://forum.evo.im/d/270-displaying-template-variables-tv-delimited-list-separator

**Comment by yanqpl** [comment]
> https://docs.evo-cms.com/en/latest/04_Extras/DocLister/01_Parameters/ - renderTv

Thanks for reply, when i added a `renderTV` parameter and still not working i have this same results ie. `"Value2||Value3"`

My code looks like below
```
&tvList=`language,localisation,category,salary,start,time,where`
&renderTv=`language,localisation,category,salary,start,time,where`
```

**Comment by yanqpl** [comment]
Any ideas? It's important to finish my project.

**Comment by Pathologic** [comment]
&renderTV

**Comment by cimt** [comment]
@Pathologic ...oh man, thank you!
I wrote it like in the documentation, then it can't work either!
&render**Tv** instead of &render**TV**
