### ISSUE TITLE
Deprecated: trim() php 8.2

### ISSUE THREAD

**Issue by TolkIT-team** [AgelxNash/DocLister#391]
При работе php 8.2 ошибка Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /assets/snippets/DocLister/core/DocLister.abstract.php on line 1324
Надо добавить `?? ''`
`$item = trim($item ?? '');`

**Comment by Pathologic** [comment]
Здесь стоит разобраться, откуда у вас в списке Id появляется null.
