### ISSUE TITLE
Создание документов в корне - udperms_allowroot

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#69]
Если модуль класс запущен не от имени главного администратора, то делать проверку на доступ к созданию документов в корне (параметр udperms_allowroot)

**Comment by Pathologic** [comment]
Web-пользователям вообще не нужно создавать документы в корне.

**Comment by AgelxNash** [comment]
Wow, а почему $fire_events = false обратно откатились до $fire_events = null ?

**Comment by Pathologic** [comment]
Потому что git в IDE не настроен, забыл файлы обновить.

**Comment by AgelxNash** [comment]
Проверь еще phpdoc

**Comment by Pathologic** [comment]
После https://github.com/AgelxNash/DocLister/commit/2e670d924a81ea0a4c90ccd642dca74d7c769fdc ничего не было, так что должно нормально все быть с phpdoc.

**Comment by AgelxNash** [comment]
В общем теперь нельзя редактировать доки в корне через MODxAPI по крону. Приходится хардкорить с авторизацией
