### ISSUE TITLE
Шаблоны и TV-параметры

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#73]
Добавить проверки на существование шаблонов и связки с TV-параметрами

**Comment by Pathologic** [comment]
TV не обязательно могут быть привязаны к шаблонам. Я когда-то собирался сделать, а @alooze вроде и сделал, привязку к parent.

**Comment by alooze** [comment]
alooze не стал связываться с самими TV в привязке к parent, а сделал
псевдо-TV, которые работают по тем же принципам, но настраиваются в модуле
и заполняются в админке для детей какого-то parent, а не для ресурсов с
нужным шаблоном.

Не знаю, откуда мне свалилось это письмо и по какому поводу, но я рад что
AN жив и в седле.

11 октября 2016 г., 4:23 пользователь Pathologic <notifications@github.com>
написал:
