### ISSUE TITLE
Пересчет menuindex

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#77]
Пересчет menuindex у документов в определенной папке по определенным критериям (по id, по дате публикации, по pagetitle, по значению tv и т.п.)

**Comment by AgelxNash** [comment]
```php
$modx->db->query("SET @index := 0");
$modx->db->query("UPDATE ".$modx->getFullTableName('site_content')." SET `menuindex` = (@index := @index + 1) WHERE `parent`=3 ORDER BY `menuindex` ASC");
$modx->db->query("SET @index := -1");

**Comment by Pathologic** [comment]
```
/**
     * @param int $parent
     * @param string $criteria
     * @param string $dir
     * @return $this
     */
    public function updateMenuindex(int $parent, $criteria = 'id', $dir = 'asc') {
        $dir = strtolower($dir) == 'desc' ? 'desc' : 'asc';
        $modx->query("SET @index := 0");
        $modx->query("UPDATE {$this->makeTable('site_content')} SET `menuindex` = (@index := @index + 1) WHERE `parent`={$parent} ORDER BY {$criteria} {$dir}");
        return $this;
    }
```

**Comment by Pathologic** [comment]
На TV стоит забить из-за геморроя с приведением типов.

**Comment by AgelxNash** [comment]
Согласен. Если приспичит отсортировать по ТВ, то можно использовать MODxAPI внутри DocLister через prepare! Во как завернул:-)

**Comment by AgelxNash** [comment]
Контроль типа int для $parent сработает только с php 7. В php 5.6 и ниже возможен контроль типов только для массива или объектов.

**Comment by Pathologic** [comment]
Кавычки для $criteria не добавлял специально, чтобы можно было вписать if для дат.

**Comment by AgelxNash** [comment]
https://scrutinizer-ci.com/g/AgelxNash/DocLister/inspections/ea14b1e5-ce0c-46e1-b770-c917bbfc5a84/issues/files/assets/lib/MODxAPI/modResource.php?status=new&orderField=path&order=asc&honorSelectedPaths=0
```
The variable $modx does not exist. Did you forget to declare it?
```

**Comment by Pathologic** [comment]
Исправил
