### ISSUE TITLE
Удаление документов из корзины через modResource

### ISSUE THREAD

**Issue by AgelxNash** [AgelxNash/DocLister#78]

**Comment by Pathologic** [comment]
Лучше добавить отдельный метод для очистки корзины, а в методе delete добавить вызов события OnDocFormDelete.

**Comment by Pathologic** [comment]
Отдельный метод уже есть, но вся логика удаления документов неправильная.

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/01bd32516354338d04ef68d64217db4ee989cb9c
